name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:

    runs-on: windows-2022
        
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd langcinternal && cargo build --release
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-windows
        path: langcinternal/target/
  build-macos:

    runs-on: macos-12
        
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd langcinternal && cargo build --release
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-macos
        path: langcinternal/target/
  build-linux:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd langcinternal && cargo build --release
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-linux
        path: langcinternal/target/

