name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Switch Directories
      run: cd langcinternal
    - name: Build
      run: cargo build --release
    - name: Go back to main dir
      run: cd ..
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          build
            /langcinternal/target/
